#存放一些web配置信息
Version: 1.0

#七牛云
#设置密钥和空间名称，默认空间为tyun，请先在七牛云创建好空间
#Chain domain 设置空间的外链域名，格式：https(http)://xxx.yourdomain.xxx
ACCESS_KEY: zVeMUFmiaTut7lySrqpKi0zsliUmWJ9hLElCxOha
SECRET_KEY: 1RXm4QajxRDLIDEOLXxjAqrT_VMDPK1Cy4s0lv5c
#文件存储空间
disk_bucket: tyun
#移动U盘存储空间
u_disk_bucket: tyun
#图床存储空间
img_bucket: img-bucket
#文件外链地址
chain_domain: http://download.90play.cn
#移动U盘外链地址
u_disk_domain: http://download.90play.cn
#图床外链地址
img_domain: https://img.90play.cn

#开启本地存储
#本地存储可能占大量空间，谨慎设置
#设置use ，启用和停止本地存储,true or false,默认为 false，不保存到本地
#设置本地存储路径，修改folder，默认为uploadFile 文件夹
LocalStorage:
  use: true
  folder: uploadFile